name: Build and deploy custom MkDocs site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Install frontend tools
        run: npm install

      - name: Build MkDocs
        run: mkdocs build

      - name: Validate HTML
        run: npm run lint:html || true

      - name: Minify HTML
        run: npm run minify:html

      - name: Build CSS with PostCSS
        run: npm run build:css

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
